name: Build Electron Apps

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: electron-app
        run: npm ci
      
      - name: Check files exist
        working-directory: electron-app
        run: |
          if (Test-Path "app/index.html") { 
            Write-Host "✅ app/index.html exists" 
          } else { 
            Write-Host "❌ app/index.html missing"
            exit 1
          }
      
      - name: Build Windows
        working-directory: electron-app
        run: npm run package-win
        continue-on-error: true
      
      - name: List dist contents
        working-directory: electron-app
        run: |
          Write-Host "📁 Contents of dist:"
          Get-ChildItem -Path dist -Recurse | Select-Object FullName
      
      - name: Upload Windows build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: electron-app/dist/InterOGE-win32-x64/
          if-no-files-found: warn

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: electron-app
        run: npm ci
      
      - name: Check files exist
        working-directory: electron-app
        run: |
          ls -la app/
          if [ -f "app/index.html" ]; then
            echo "✅ app/index.html exists"
          else
            echo "❌ app/index.html missing"
            exit 1
          fi
      
      - name: Build Linux
        working-directory: electron-app
        run: npm run package-linux
        continue-on-error: true
      
      - name: List dist contents
        working-directory: electron-app
        run: |
          echo "📁 Contents of dist:"
          ls -lah dist/ || true
      
      - name: Create tar.gz if build succeeded
        working-directory: electron-app
        run: |
          if [ -d "dist/InterOGE-linux-x64" ]; then
            cd dist
            tar -czf InterOGE-Linux-x64.tar.gz InterOGE-linux-x64/
            echo "✅ Archive created"
          else
            echo "⚠️ Build directory not found"
          fi
      
      - name: Upload Linux build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            electron-app/dist/InterOGE-linux-x64/
            electron-app/dist/*.tar.gz
          if-no-files-found: warn

  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: electron-app
        run: npm ci
      
      - name: Check files exist
        working-directory: electron-app
        run: |
          ls -la app/
          if [ -f "app/index.html" ]; then
            echo "✅ app/index.html exists"
          else
            echo "❌ app/index.html missing"
            exit 1
          fi
      
      - name: Build macOS
        working-directory: electron-app
        run: npm run package-mac
        continue-on-error: true
      
      - name: List dist contents
        working-directory: electron-app
        run: |
          echo "📁 Contents of dist:"
          ls -lah dist/ || true
      
      - name: Upload macOS build
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: electron-app/dist/InterOGE-darwin-x64/
          if-no-files-found: warn

